prgrms-web-devcourse-final-project/WEB1_2_Child-Learn_BE

src/main/java/com/prgrms/ijuju/test/Test.java
src/main/java/com/prgrms/ijuju/test/TestPR.java

PR 테스트
<br>
<br>
<br>
<br>
<br>
<br>
issue 및 pr 테스트 입니다.
1. 통합 브랜치를 만들지 않고 하위 브랜치를 병합.
SCRUM-49에 SCRUM-48을 병합하여 진행하였습니다.
2. 병합한 브랜치를 PR 올렸을 때 기타 브랜치의 상황 파악
<br>

[Test] PR TEST

---

src/main/java/com/prgrms/ijuju/test/Test.java
src/main/java/com/prgrms/ijuju/test/TestPR.java

Reverts prgrms-web-devcourse-final-project/WEB1_2_Child-Learn_BE#23

Revert "[Test] PR TEST"

---

src/main/java/com/prgrms/ijuju/domain/stock/adv/advstock/controller/AdvStockController.java
src/main/java/com/prgrms/ijuju/domain/stock/adv/stockrecord/controller/StockRecordController.java
src/main/java/com/prgrms/ijuju/domain/stock/adv/stockrecord/service/StockRecordServiceImpl.java

<br>
> 실행 테스트 이상 없음
<br>
<br>
<br>
<br>

[Refactor] AdvInvest 오류 수정

---

src/main/java/com/prgrms/ijuju/domain/ranking/controller/RankingController.java
src/main/java/com/prgrms/ijuju/domain/stock/mid/controller/MidStockController.java
src/main/java/com/prgrms/ijuju/domain/stock/mid/dto/response/ErrorMidResponse.java
src/main/java/com/prgrms/ijuju/domain/stock/mid/service/MidStockTradeService.java
src/main/java/com/prgrms/ijuju/global/error/GlobalExceptionHandler.java

https://github.com/prgrms-web-devcourse-final-project/WEB1_2_Child-Learn_BE/issues/64 중급 멤버아이디변경 및 예외처리
<br>
<br>
<br>
<br>
<br>
<br>
<br>

[Refactor] 중급 주식 멤버아이디변경 및 예외처리

---

src/main/java/com/prgrms/ijuju/domain/avatar/controller/ItemController.java
src/main/java/com/prgrms/ijuju/domain/avatar/dto/request/ItemRequestDTO.java
src/main/java/com/prgrms/ijuju/domain/avatar/entity/Item.java
src/main/java/com/prgrms/ijuju/domain/avatar/entity/Purchase.java
src/main/java/com/prgrms/ijuju/domain/avatar/exception/ItemException.java
src/main/java/com/prgrms/ijuju/domain/avatar/repository/PurchaseRepository.java
src/main/java/com/prgrms/ijuju/domain/avatar/service/AvatarService.java
src/main/java/com/prgrms/ijuju/domain/avatar/service/ItemService.java
src/main/java/com/prgrms/ijuju/domain/member/entity/Member.java
src/main/java/com/prgrms/ijuju/domain/member/service/MemberService.java

<br>
<br>
<br>
<br>
<br>
<br>
import 문 삭제로 다시 PR 올립니다.
<br>

[Fix] avatar import문 수정

---

src/main/java/com/prgrms/ijuju/domain/minigame/oxquiz/oxquizdata/config/OXQuizDataInitializer.java
src/main/java/com/prgrms/ijuju/domain/minigame/oxquiz/oxquizdata/entity/OXQuizData.java
src/main/java/com/prgrms/ijuju/domain/minigame/oxquiz/oxquizdata/repository/OXQuizDataRepository.java
src/main/java/com/prgrms/ijuju/domain/minigame/oxquiz/oxquizprogression/constant/Priority.java
src/main/java/com/prgrms/ijuju/domain/minigame/oxquiz/oxquizprogression/controller/OXQuizProgressionController.java
src/main/java/com/prgrms/ijuju/domain/minigame/oxquiz/oxquizprogression/dto/request/QuizRequestDto.java
src/main/java/com/prgrms/ijuju/domain/minigame/oxquiz/oxquizprogression/dto/response/QuizResponseDto.java
src/main/java/com/prgrms/ijuju/domain/minigame/oxquiz/oxquizprogression/entity/OXQuizProgression.java
src/main/java/com/prgrms/ijuju/domain/minigame/oxquiz/oxquizprogression/repository/OXQuizProgressionRepository.java
src/main/java/com/prgrms/ijuju/domain/minigame/oxquiz/oxquizprogression/scheduler/OXQuizProgressionScheduler.java
src/main/java/com/prgrms/ijuju/domain/minigame/oxquiz/oxquizprogression/service/OXQuizProgressionService.java
src/main/java/com/prgrms/ijuju/domain/minigame/oxquiz/oxquizprogression/service/OXQuizProgressionServiceImpl.java
src/main/java/com/prgrms/ijuju/global/config/ApiSecurityConfigTest.java
src/main/resources/application.yml
src/main/resources/minigame-data/ox-quiz.json

<br>
<br>
- **역할**: OX 퀴즈 문제 데이터를 저장하는 엔티티 클래스.
- **필드**:
- `id`: 퀴즈 문제의 고유 ID (Primary Key).
- `question`: 문제 내용.
- `answer`: 정답 (O 또는 X).
- `explanation`: 정답에 대한 설명.
- `difficulty`: 문제 난이도 (easy, medium, hard).
- **설명**: 이 클래스는 퀴즈의 문제와 관련된 모든 정보를 저장하며, `OXQuizProgression` 클래스와 연관이 있습니다.
- **역할**: 유저별 진행 상태를 저장하는 엔티티 클래스.
- **필드**:
- `id`: 진행 상태의 고유 ID (Primary Key).
- `memberId`: 유저 ID.
- `oxQuizData`: 연관된 퀴즈 데이터 (`OXQuizData`).
- `isCorrect`: 사용자가 푼 문제의 정답 여부 (맞으면 `true`, 틀리면 `false`).
- `priority`: 퀴즈의 우선순위 (LOW 또는 HIGH).
- `attemptDate`: 퀴즈를 푼 날짜.
- **설명**: 이 클래스는 각 유저가 풀었던 퀴즈의 진행 상태와 정답 여부, 우선순위 정보를 저장합니다.
- **역할**: OX 퀴즈 진행 상태와 관련된 서비스 인터페이스.
- **메서드**:
- `getProgressionsByMemberId(Long memberId)`: 유저 ID에 해당하는 퀴즈 진행 상태를 반환.
- …

[Feat] OX 퀴즈 기능 구현

---

build.gradle
src/main/java/com/prgrms/ijuju/domain/chat/entity/Chat.java
src/main/java/com/prgrms/ijuju/domain/chat/exception/ChatException.java
src/main/java/com/prgrms/ijuju/domain/chat/service/ChatService.java
src/main/java/com/prgrms/ijuju/domain/friend/dto/response/FriendResponseDTO.java
src/main/java/com/prgrms/ijuju/domain/friend/entity/FriendRequest.java
src/main/java/com/prgrms/ijuju/domain/friend/entity/FriendshipStatus.java
src/main/java/com/prgrms/ijuju/domain/friend/exception/FriendException.java
src/main/java/com/prgrms/ijuju/domain/friend/service/FriendService.java
src/main/java/com/prgrms/ijuju/domain/member/controller/MemberController.java
src/main/java/com/prgrms/ijuju/domain/member/dto/response/MemberResponseDTO.java
src/main/java/com/prgrms/ijuju/domain/member/repository/MemberRepository.java
src/main/java/com/prgrms/ijuju/domain/member/service/MemberService.java
src/main/java/com/prgrms/ijuju/domain/stock/mid/service/MidStockTradeService.java
src/main/java/com/prgrms/ijuju/domain/wallet/entity/Wallet.java
src/main/java/com/prgrms/ijuju/domain/wallet/exception/WalletException.java
src/main/java/com/prgrms/ijuju/domain/wallet/service/TransactionService.java
src/main/java/com/prgrms/ijuju/domain/wallet/service/WalletService.java
src/main/java/com/prgrms/ijuju/global/exception/CustomException.java
src/main/java/com/prgrms/ijuju/global/exception/GlobalExceptionHandler.java

- 친구 요청 처리 후 이벤트 에러 해결
- 친구 관련 기능 추가
- 예외 처리 코드 리팩토링
<br>
<br>
- 친구 요청 처리 후 취소 처리 불가
- 친구 요청 처리 후 친구 관계일 때 추가 요청 불가
- 사용자 목록에서 친구 여부 확인 가능
- 응답 시 단순 예외 처리 메시지 확인 가능
- 친구 요청 처리 후 취소 처리 불가  
- 요청 처리 후 요청 목록에서 제거 됨  
- 친구 요청 처리 후 친구 관계일 때 추가 요청 불가  
- 사용자 목록에서 친구 여부 확인 가능, 전체 사용자 목록에서 본인 제외하고 조회 기능 추가  
- 요청 목록에서 보낸사람, 받는사람 username 조회가능  
<br>
<br>
전체 사용자 목록에서 친구 요청 상태 및 친구 상태에 따른 친구 요청 보내기 기능 구현 요청이 들어왔음
<br>
<br>

[Refacor] Friend 친구 관련 기능 추가 및 예외 처리 코드 리팩토링

---

src/main/java/com/prgrms/ijuju/domain/stock/mid/config/InitMidDb.java
src/main/java/com/prgrms/ijuju/domain/stock/mid/controller/MidStockController.java
src/main/java/com/prgrms/ijuju/domain/stock/mid/repository/MidStockPriceRepositoryImpl.java

(https://github.com/prgrms-web-devcourse-final-project/WEB1_2_Child-Learn_BE/issues/83) 
<br>
<br>
<br>
<br>
<br>
<br>

[Fix] 중급 주식 데이터 서버측 생성 버그 픽스

---

src/main/java/com/prgrms/ijuju/domain/stock/begin/controller/BeginStockController.java

모의 투자 초급에서 스케줄러 기능이 동작하지 않는 경우, 수동으로 생성하는 API의 조건이
기존 ROLE 확인 방식에서, ROLE을 사용하지 않게 되어 특정 key값을 확인하는 것으로 변경했습니다.
<br>
<br>
<br>
<br>
<br>
<br>
<br>

[Refactor] 모의 투자 초급 오늘의 데이터 수동 생성 API 조건 변경

---

src/main/java/com/prgrms/ijuju/domain/minigame/wordquiz/service/WordQuizService.java

로직 변경이후 조회만 하지 않음에도 불구하고 readOnly 어노테이션이 있어 버그 발생
<br>
<br>
<br>
<br>
<br>
<br>
작업한 도메인을 또 깜빡하고 커밋 메세지에 안넣었습니다 ㅜ 죄송합니다!
<br>

[Fix] 낱말 게임 readOnly 어노테이션 제거

---

src/main/java/com/prgrms/ijuju/global/config/WebSocketConfig.java

url 오류가 있어 수정을 합니다
<br>
<br>
<br>
<br>
<br>
<br>
<br>

[Fix] webSocket config url 변경

---

src/main/java/com/prgrms/ijuju/global/auth/JwtHandshakeInterceptor.java
src/main/java/com/prgrms/ijuju/global/config/ApiSecurityConfig.java
src/main/java/com/prgrms/ijuju/global/config/WebSocketConfig.java

JwtHandshakeInterceptor 구현을 완료하였으며, WebSocketConfig 와 ApiSecurityConfig 수정을 완료하였습니다.
related to: #120
<br>
<br>
<br>
> JWT 키 인증 관련 문제라 배포 서버에서 테스트를 바로 진행할 예정입니다
<br>
<br>
<br>
<br>

Feat: JwtHandshakeInterceptor 기능 구현

---

src/main/java/com/prgrms/ijuju/global/auth/JwtHandshakeInterceptor.java

Bearer 처리 로직상 문제가 생겨 픽스하였습니다
related to: #120
<br>
<br>
<br>
<br>
<br>
<br>
<br>

[Fix] Interceptor Bearer 키워드 처리 로직 변경

---

src/main/java/com/prgrms/ijuju/domain/stock/begin/service/BeginStockService.java

배포 서버에서 퀴즈 로그로 확인하면서 테스트 예정
<br>
<br>
<br>
<br>
<br>
<br>
<br>

[Refactor] 선택된 퀴즈를 확인하기 위한 로깅 추가

---

src/main/java/com/prgrms/ijuju/global/auth/JwtHandshakeInterceptor.java

[Fix] Interceptor 가 헤더값을 받는 오류 수정

---

src/main/java/com/prgrms/ijuju/global/auth/JwtHandshakeInterceptor.java

<br>
<br>
<br>
<br>
<br>
<br>
<br>

[Fix] interceptor 에서 '+' 를 string 으로 받는 문제 해결

---

src/main/java/com/prgrms/ijuju/global/auth/JwtHandshakeInterceptor.java

<br>
<br>
<br>
<br>
<br>
<br>
<br>

[Fix]Interceptor 에 url decoder 추가

---

src/main/java/com/prgrms/ijuju/global/config/MongoConfig.java

<br>
<br>
<br>
<br>
<br>
<br>
<br>

[Fix] MongoDB URI 설정값 주입을 위한 value 적용

---

src/main/java/com/prgrms/ijuju/domain/stock/begin/service/BeginStockPriceService.java

> 변경 사항 및 관련 이슈에 대해 간단하게 작성해주세요. 어떻게보다 무엇을 왜 수정했는지 설명해주세요. 
스케줄링 기준이 엔티티 수정 이전 기준으로 작성되어 있어, 현재 스케줄링 기능이 제대로 동작하지 않아 수정하였습니다.
<br>
<br>
데이터는 항상 -3일 ~ +3일이 존재해야하며,
init 데이터는 서버 시작 시에 repo가 비어 있는 경우 오늘을 기준으로 -3일 ~ +3일의 일주일 데이터가 생성됩니다.
이후부터는 마지막 날짜의 -2일인 날의 자정에 해당 날을 기준으로 +3일이 되는 날부터 일주일의 데이터가 생성되고,
이후부터는 일주일마다 반복됩니다.
<br>
<br>
<br>
<br>
<br>

[Fix] 모의 투자 초급 스케줄링 기준 수정

---

src/main/java/com/prgrms/ijuju/global/auth/JwtHandshakeInterceptor.java

Authorization 을 대문자, 소문자 둘 다 처리 할 수 있도록 수정하였습니다 
<br>
<br>
<br>
<br>
<br>
<br>
<br>

[fix] Intercerptor 대문자 처리 코드 추가

---

src/main/java/com/prgrms/ijuju/global/auth/WebsocketChannelInterceptor.java
src/main/java/com/prgrms/ijuju/global/config/WebSocketConfig.java

JWT 토큰 인증 과정을 좀 더 자세히 다루기 위해 ChannelInterceptor 를 추가합니다 
<br>
<br>
<br>
<br>
<br>
<br>
<br>

[Feat] WebsocketChannelInterceptor 구현

---

src/main/java/com/prgrms/ijuju/global/auth/JwtHandshakeInterceptor.java
src/main/java/com/prgrms/ijuju/global/config/WebSocketConfig.java

충돌 오류를 수정했습니다.
로그를 추가 기입했습니다
<br>
<br>
<br>
<br>
<br>
<br>
<br>

[Fix] webSocketConfig 충돌 오류 수정 및 log 추가

---

src/main/java/com/prgrms/ijuju/global/auth/JwtHandshakeInterceptor.java

<br>
<br>
<br>
<br>
<br>
<br>
<br>

[Fix] Interceptor 에서 access_token 을 받을 수 있게 수정

---

src/main/java/com/prgrms/ijuju/domain/stock/adv/advancedinvest/exception/AdvancedInvestErrorCode.java
src/main/java/com/prgrms/ijuju/domain/stock/adv/advancedinvest/exception/AdvancedInvestException.java
src/main/java/com/prgrms/ijuju/domain/stock/adv/advancedinvest/exception/gameexception/GameAlreadyPlayedException.java
src/main/java/com/prgrms/ijuju/domain/stock/adv/advancedinvest/exception/gameexception/GameNotFoundException.java
src/main/java/com/prgrms/ijuju/domain/stock/adv/advancedinvest/exception/gameexception/InvalidGameTimeException.java
src/main/java/com/prgrms/ijuju/domain/stock/adv/advancedinvest/exception/otherexception/DataNotInitializedException.java
src/main/java/com/prgrms/ijuju/domain/stock/adv/advancedinvest/exception/otherexception/MemberNotFoundException.java
src/main/java/com/prgrms/ijuju/domain/stock/adv/advancedinvest/exception/otherexception/SessionNotFoundException.java
src/main/java/com/prgrms/ijuju/domain/stock/adv/advancedinvest/exception/otherexception/TransactionFailedException.java
src/main/java/com/prgrms/ijuju/domain/stock/adv/advancedinvest/exception/stockexception/DataNotFoundException.java
src/main/java/com/prgrms/ijuju/domain/stock/adv/advancedinvest/exception/stockexception/InsufficientStockException.java
src/main/java/com/prgrms/ijuju/domain/stock/adv/advancedinvest/exception/stockexception/InvalidQuantityException.java
src/main/java/com/prgrms/ijuju/domain/stock/adv/advancedinvest/exception/stockexception/StockNotFoundException.java
src/main/java/com/prgrms/ijuju/domain/stock/adv/advancedinvest/service/AdvancedInvestServiceImpl.java
src/main/java/com/prgrms/ijuju/domain/stock/adv/advstock/exception/AdvStockErrorCode.java
src/main/java/com/prgrms/ijuju/domain/stock/adv/advstock/exception/stockexception/EmptyStockDataException.java
src/main/java/com/prgrms/ijuju/domain/stock/adv/advstock/exception/stockexception/InvalidTradeHourException.java
src/main/java/com/prgrms/ijuju/domain/stock/adv/advstock/exception/stockexception/LiveDataNotFoundException.java
src/main/java/com/prgrms/ijuju/domain/stock/adv/advstock/exception/stockexception/ReferenceDataNotFoundException.java
src/main/java/com/prgrms/ijuju/domain/stock/adv/advstock/exception/stockexception/StockDataMismatchException.java
src/main/java/com/prgrms/ijuju/domain/stock/adv/advstock/exception/stockexception/StockSaveFailedException.java
src/main/java/com/prgrms/ijuju/domain/stock/adv/advstock/scheduler/AdvStockScheduler.java
src/main/java/com/prgrms/ijuju/domain/stock/adv/advstock/service/AdvStockServiceImpl.java
src/main/java/com/prgrms/ijuju/domain/stock/adv/stockrecord/exception/StockRecordErrorCode.java
src/main/java/com/prgrms/ijuju/domain/stock/adv/stockrecord/exception/stockrecordexception/MemberNotFoundException.java
src/main/java/com/prgrms/ijuju/domain/stock/adv/stockrecord/exception/stockrecordexception/RecordNotFoundException.java
src/main/java/com/prgrms/ijuju/domain/stock/adv/stockrecord/exception/stockrecordexception/RecordSaveFailedException.java
src/main/java/com/prgrms/ijuju/domain/stock/adv/stockrecord/service/StockRecordServiceImpl.java

<br>
<br>
<br>
<br>
<br>
<br>
<br>

[Refactor] Advanced Invest Custom Exception 구현

---

src/main/java/com/prgrms/ijuju/domain/avatar/controller/ItemController.java
src/main/java/com/prgrms/ijuju/domain/avatar/service/ItemService.java

<br>
<br>
<br>
<br>
<br>
<br>
아이템 목록 조회에 대한 2개의 파일 수정사항이 있습니다.
<br>

[Feat] 아이템 목록 조회 구현

---

src/main/java/com/prgrms/ijuju/domain/stock/adv/advancedinvest/handler/AdvancedInvestWebSocketHandler.java

<br>
<br>
br>
<br>
<br>
<br>
<br>

[Refactor] AdvancedInvest Handler Log 추가

---

src/main/java/com/prgrms/ijuju/domain/notification/controller/SseNotificationController.java
src/main/java/com/prgrms/ijuju/domain/notification/exception/NotificationErrorCode.java
src/main/java/com/prgrms/ijuju/domain/notification/repository/EmitterRepository.java
src/main/java/com/prgrms/ijuju/domain/notification/service/NotificationService.java
src/main/java/com/prgrms/ijuju/domain/notification/service/SseNotificationService.java

https://github.com/prgrms-web-devcourse-final-project/WEB1_2_Child-Learn_BE/issues/152 커넥션풀 고려 sse 연결시간 수정
<br>
<br>
<br>

[Fix] sse 연결 설정 수정

---

src/main/java/com/prgrms/ijuju/domain/chat/controller/ChatController.java
src/main/java/com/prgrms/ijuju/domain/chat/scheduler/RedisHealthCheckScheduler.java
src/main/java/com/prgrms/ijuju/domain/chat/service/ChatSessionService.java
src/main/java/com/prgrms/ijuju/global/config/ApiSecurityConfig.java
src/main/resources/application-dev.yml

Chat 엔드포인트에 Redis 연결 테스트 추가
<br>
<br>
<br>
<br>
<br>
<br>
<br>

[Feat] Chat 엔드포인트에 Redis 연결 테스트 추가

---

src/main/java/com/prgrms/ijuju/domain/member/controller/MemberController.java
src/main/java/com/prgrms/ijuju/domain/member/repository/MemberRepository.java
src/main/java/com/prgrms/ijuju/domain/member/service/MemberService.java
src/main/java/com/prgrms/ijuju/domain/stock/adv/advstock/service/AdvStockServiceImpl.java

회원검색 시 본인 제외로 수정
<br>
<br>
<br>
<br>
<br>
<br>
<br>

[Refactor] Member 회원검색 시 본인 제외로 수정

---

src/main/java/com/prgrms/ijuju/domain/stock/adv/advancedinvest/handler/AdvancedInvestWebSocketHandler.java

<br>
<br>
<br>
<br>
<br>
<br>
<br>

[Fix] AdvInvest Handler, 잘못된 요청 무시 구현

---

src/main/java/com/prgrms/ijuju/domain/stock/adv/advstock/scheduler/AdvStockScheduler.java
src/main/java/com/prgrms/ijuju/domain/stock/adv/advstock/util/DateUtil.java

<br>
<br>
<br>
<br>
<br>
<br>
<br>

Fix: AdvStock 주말에 데이터 안날라오는 오류 수정

---

src/main/java/com/prgrms/ijuju/domain/notification/service/SseNotificationService.java

Refactor: sse 재연결 타임 1초에서 3초로 변경

---

src/main/java/com/prgrms/ijuju/domain/notification/service/SseNotificationService.java

Fix: sse 재연결시 의미있는 데이터 전송으로 변경

---

src/main/java/com/prgrms/ijuju/domain/notification/controller/SseNotificationController.java

Fix: 프론트 요청으로 컨틀롤러 반환타입 변경

---

src/main/java/com/prgrms/ijuju/domain/notification/controller/SseNotificationController.java

Refactor: sse 응답헤더 설정

---

src/main/java/com/prgrms/ijuju/domain/notification/service/SseNotificationService.java

Feat: sse 하트 비트 설정

---

src/main/java/com/prgrms/ijuju/domain/infra/controller/HealthCheckController.java

alb 헬스체크 위해 컨트롤러 생성
<br>
<br>
<br>
<br>
<br>
<br>
<br>

[Feat] infra 헬스체크 기능 구현

---

src/main/java/com/prgrms/ijuju/global/config/ApiSecurityConfig.java

헬스체크 시큐리티 인증 제외
<br>
<br>
<br>
<br>
<br>
<br>
<br>

[Feat] 헬스체크 시큐리티 인증 제외 추가

---

src/main/java/com/prgrms/ijuju/domain/notification/service/SseNotificationService.java

Refactor: sse 에러 로그 수정

---

src/main/java/com/prgrms/ijuju/domain/article/scheduler/ArticleScheduler.java
src/main/java/com/prgrms/ijuju/domain/stock/adv/advstock/scheduler/AdvStockScheduler.java

<br>
<br>
ex) a를 위해 b를 구현해서 c를 작동하게 했습니다.
<br>
<br>
<br>
<br>
<br>

[Fix] Article / AdvInvest Scheduler 시간 변경

---

src/main/java/com/prgrms/ijuju/domain/article/scheduler/ArticleScheduler.java
src/main/java/com/prgrms/ijuju/domain/stock/adv/advstock/scheduler/AdvStockScheduler.java

<br>
<br>
<br>
<br>
<br>
<br>
<br>

fix: Article / Adv-Invest 스케쥴러 시간 변경 / 로그 추가

---

src/main/java/com/prgrms/ijuju/domain/article/scheduler/ArticleScheduler.java
src/main/java/com/prgrms/ijuju/domain/stock/adv/advstock/scheduler/AdvStockScheduler.java

Fix: Article / AdvStock 스케쥴러 시간 변경

---

src/main/java/com/prgrms/ijuju/domain/avatar/dto/response/ItemResponseDTO.java
src/main/java/com/prgrms/ijuju/domain/avatar/entity/Avatar.java
src/main/java/com/prgrms/ijuju/domain/avatar/entity/Purchase.java
src/main/java/com/prgrms/ijuju/domain/avatar/service/AvatarService.java
src/main/java/com/prgrms/ijuju/domain/avatar/service/ItemService.java
src/main/java/com/prgrms/ijuju/domain/member/controller/MemberController.java
src/main/java/com/prgrms/ijuju/domain/member/dto/request/MemberRequestDTO.java
src/main/java/com/prgrms/ijuju/domain/member/entity/Member.java
src/main/java/com/prgrms/ijuju/domain/member/service/MemberService.java

- 프론트와의 연결을 위해 반환값을 추가했고, 서비스 로직을 수정했습니다.
<br>
<br>
<br>
<br>
<br>
<br>
- 엔티티 필드를 추가했습니다. 관련된 부분이 있으신 분들은 참고 부탁드립니다!
<br>

[Refactor] 아이템 구매/장착/해제 시 반환 값 추가

---

src/main/java/com/prgrms/ijuju/domain/article/exception/ArticleErrorCode.java
src/main/java/com/prgrms/ijuju/domain/article/exception/ArticleGenerationException.java
src/main/java/com/prgrms/ijuju/domain/article/exception/ArticleNotFoundException.java
src/main/java/com/prgrms/ijuju/domain/article/service/ArticleGenerationService.java
src/main/java/com/prgrms/ijuju/domain/article/service/ArticleService.java
src/main/java/com/prgrms/ijuju/domain/article/service/StockTrendService.java
src/main/java/com/prgrms/ijuju/domain/minigame/oxquiz/oxquizprogression/exception/OXQuizErrorCode.java
src/main/java/com/prgrms/ijuju/domain/minigame/oxquiz/oxquizprogression/exception/OXQuizInvalidAnswerException.java
src/main/java/com/prgrms/ijuju/domain/minigame/oxquiz/oxquizprogression/exception/OXQuizNotFoundException.java
src/main/java/com/prgrms/ijuju/domain/minigame/oxquiz/oxquizprogression/service/OXQuizProgressionService.java
src/main/java/com/prgrms/ijuju/domain/stock/adv/advancedinvest/exception/AdvancedInvestErrorCode.java
src/main/java/com/prgrms/ijuju/domain/stock/adv/advancedinvest/exception/gameexception/GameAlreadyStartedException.java
src/main/java/com/prgrms/ijuju/domain/stock/adv/advancedinvest/service/AdvancedInvestServiceImpl.java

<br>
<br>
<br>
> PostMan 에서 일부로 데이터를 지우고 실행하여 Exception 전부 실행 문제 없이 되는 점을 확인
<br>
<br>
<br>
<br>

[Refactor] AdvInvest / Article / OxQuiz 커스텀 예외 처리 구현

---

src/main/java/com/prgrms/ijuju/domain/stock/adv/advancedinvest/service/AdvancedInvestServiceImpl.java

<br>
<br>
<br>
> 
<br>
<br>
<br>
<br>

[Fix] AdvancedInvest 반복 재연결 오류 수정

---

src/main/java/com/prgrms/ijuju/domain/stock/adv/advancedinvest/service/AdvancedInvestServiceImpl.java

클라이언트 측에서 json 아 아닌 데이터를 받는 로직에 문제가 생겨, json 이 아닌 데이터는 날리지 않는 방향으로 수정하였습니다.
related to: #161
<br>
<br>
<br>
<br>
<br>
<br>
<br>

[Fix] AdvancedInvest 메시지 전송 오류 픽스

---

src/main/java/com/prgrms/ijuju/domain/stock/mid/controller/MidStockController.java
src/main/java/com/prgrms/ijuju/domain/stock/mid/service/MidStockTradeService.java

(https://github.com/prgrms-web-devcourse-final-project/WEB1_2_Child-Learn_BE/issues/187) 중급 주식 매도 반환값 변경
<br>
<br>
<br>

[Refactor] 중급 주식 매도 반환값 변경
